export const dreambidFeatures = [
    {
        image1 : "/images/dreambid2.png",
        image2 : "/images/dreambid1.png",
        title : "Middleware Authentication",
        description : "Implemented middleware authentication to secure routes, ensuring only authorized users can access protected areas of the application.",
        image1Class : "w-6/12",
        image2Class : "w-8/12 -bottom-20 ",
        mb : "mb-20"
    },
    {
        image1 : "/images/dreambid3.png",
        image2 : "/images/dreambid4.png",
        title : "CRUD Operations",
        description : "Engineered a backend hub for seamless Create, Read, Update, and Delete operations, putting control in the hands of users.",
        image1Class : "w-8/12",
        image2Class : "w-8/12 -bottom-20 ",
        mb : "mb-20"
    },
    {
        image1 : "/images/dreambid5.png",
        image2 : "/images/dreambid6.png",
        title : "Instant Notifications",
        description : "Boosted engagement with Laravel's queueable notifications, delivering instant alerts for successful listings and incoming bids.",
        image1Class : "w-6/12",
        image2Class : "w-10/12 -bottom-32",
        mb : "mb-32"
    },
    {
        image1 : "/images/dreambid7.png",
        image2 : "/images/dreambid8.png",
        title : "Responsive Payment Calculator",
        description : "Provided users with immediate financial insights during bids using a dynamic payment calculator with JS.",
        image1Class : "w-9/12",
        image2Class : "w-9/12 -bottom-40",
        mb : "mb-40"
    },
    {
        image1 : "/images/dreambid9.png",
        image2 : "/images/dreambid10.png",
        title : "Effortless Search",
        description : "Enabled effortless exploration with a powerful search feature using Laravel's \"Like\" query.",
        image1Class : "w-9/12",
        image2Class : "w-9/12 -bottom-56",
        mb : "mb-56"
    },
    {
        image1 : "/images/dreambid11.png",
        image2 : "/images/dreambid12.png",
        title : "Google Maps Integration",
        description : "Enhanced user experience by visually displaying listing locations on an interactive map.",
        image1Class : "w-8/12",
        image2Class : "w-10/12  -bottom-44 ",
        mb : "mb-44"
    },
    {
        image1 : "/images/dreambid13.png",
        image2 : "/images/dreambid14.png",
        title : "Inertia.js (CSR)",
        description : "Unleashed dynamic frontend experiences with Inertia.js, ensuring seamless, client-side rendering for optimized interactions.",
        image1Class : "w-7/12",
        image2Class : "w-9/12 -bottom-48 ",
        mb : "mb-48"
    }
]

export const moviebiteFeatures = [
  {
    image1: "/images/moviebites1.png",
    image2: "/images/moviebites2.png",
    title: "TMDB API Integration",
    description: "Utilized Laravel HTTP to seamlessly integrate TMDB API, offering a curated collection of movies and TV shows with comprehensive details.",
    image1Class: "w-9/12",
    image2Class: "w-9/12 -bottom-32 ",
    mb: "mb-32",
},
  {
    image1: "/images/moviebites3.png",
    image2: "/images/moviebites4.png",
    title: "Search Functionality",
    description: "Easily find specific content through the website's efficient TMDB API-powered search functionality.",
    image1Class: "w-9/12",
    image2Class: "w-9/12 -bottom-32 ",
    mb: "mb-32",
  },
  {
    image1: "/images/moviebites5.png",
    image2: "/images/moviebites6.png",
    title: "Dynamic Filtering",
    description: "Enjoy a personalized experience with dynamic filtering, leveraging TMDB API query parameters for precise results.",
    image1Class: "w-8/12",
    image2Class: "w-9/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/moviebites7.png",
    image2: "/images/moviebites8.png",
    title: "Secure Authentication",
    description: "Implemented a robust login system using Laravel's database auth and Socialite for secure and convenient access.",
    image1Class: "w-5/12",
    image2Class: "w-10/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/moviebites9.png",
    image2: "/images/moviebites10.png",
    title: "Responsive Design",
    description: "Tailwind CSS ensures a consistent and user-friendly interface across desktop, tablet, and mobile devices.",
    image1Class: "w-5/12 pr-16 rounded-2xl",
    image2Class: "w-9/12 -bottom-10",
    mb: "mb-10",
  },
  {
    image1: "/images/moviebites11.png",
    image2: "/images/moviebites12.png",
    title: "Infinite Scrolling",
    description: "Enhance user experience with infinite scrolling, eliminating the need for traditional pagination.",
    image1Class: "w-8/12",
    image2Class: "w-7/12 -bottom-20",
    mb: "mb-40",
  }
];

export const biolinkFeatures = [
  {
    image1: "/images/biolink1.png",
    image2: "/images/biolink2.png",
    title: ".NET REST API",
    description: ".NET 7 API backend forms the reliable foundation of our event platform, ensuring seamless communication, data handling, and storage.",
    image1Class: "w-5/12",
    image2Class: "w-6/12 -bottom-7 right-20",
    mb: "mb-7",
  },
  {
    image1: "/images/biolink3.png",
    image2: "/images/biolink4.png",
    title: "Spline 3D Integration",
    description: "Elevate user experience with Spline, integrating dynamic 3D elements for an immersive and visually captivating web design.",
    image1Class: "w-9/12",
    image2Class: "w-4/12 -bottom-10 left-20",
    mb: "mb-10",
  },
  {
    image1: "/images/biolink5.png",
    image2: "/images/biolink6.png",
    title: "NextAuth Login",
    description: "Streamlined user access with NextAuth, ensuring ease of entry while maintaining the highest standards of security and privacy.",
    image1Class: "w-7/12",
    image2Class: "w-8/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/biolink7.png",
    image2: "/images/biolink8.png",
    title: "API Fetch",
    description: "Empower the frontend with efficient data retrieval using the Fetch API, ensuring real-time updates and a seamless user experience.",
    image1Class: "w-9/12 rounded-2xl",
    image2Class: "w-10/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/biolink9.png",
    image2: "/images/biolink10.png",
    title: "CORS Policy",
    description: "Implement secure and controlled data sharing with CORS policy, only authorized domain can access the Backend.",
    image1Class: "w-6/12 mx-auto",
    image2Class: "w-7/12 right-1/2 translate-x-1/2 mt-5",
    mb: "mb-80",
  },
  {
    image1: "/images/biolink11.png",
    image2: "/images/biolink12.png",
    title: "Formik Validation (Yup)",
    description: "Formik integration provides real-time validation, enhancing user confidence in submitting event-related data for an improved overall experience.",
    image1Class: "w-7/12",
    image2Class: "w-8/12 -bottom-12",
    mb: "mb-12",
  },
  {
    image1: "/images/biolink13.png",
    image2: "/images/biolink14.png",
    title: "Comment (SignalR)",
    description: "Real-time engagement with SignalR chat commenting.",
    image1Class: "w-8/12",
    image2Class: "w-9/12 -bottom-44",
    mb: "mb-44",
  },
  {
    image1: "/images/biolink15.png",
    image2: "/images/biolink16.png",
    title: "Join Event",
    description: "Join event posted by other users.",
    image1Class: "w-8/12",
    image2Class: "w-9/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/biolink17.png",
    image2: "/images/biolink18.png",
    title: "Post Event",
    description: "Empower users to create and share events seamlessly with dynamic API calls, showcasing new events and fostering a diverse calendar of activities.",
    image1Class: "w-7/12",
    image2Class: "w-7/12 -bottom-48",
    mb: "mb-48",
  },
  {
    image1: "/images/biolink19.png",
    image2: "/images/biolink20.png",
    title: "Model Relationship",
    description: "Define relationships like One-One, Many-One or Many-Many in the domain, and easily fetch relevant information with 1 step.",
    image1Class: "w-9/12",
    image2Class: "w-8/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/biolink21.png",
    image2: "/images/biolink22.png",
    title: "MediatR Code Pattern",
    description: "Embrace modular and organized code with MediatR, enhancing maintainability and scalability through a clean separation of concerns in the development process.",
    image1Class: "w-10/12 mx-auto",
    image2Class: "w-11/12 mt-5 right-1/2 translate-x-1/2",
    mb: "mb-48",
  },
];

export const locationFeatures = [
  {
    image1: "/images/loc1.png",
    image2: "/images/loc2.png",
    title: "React Native Cross-Platform",
    description: "Develop a cross-platform app with React Native for unified deployment.",
    image1Class: "w-4/12",
    image2Class: "w-10/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/loc3.png",
    image2: "/images/loc4.png",
    title: "Laravel Eloquent Query",
    description: "Optimize Laravel API with eloquent relationships for efficient data handling.",
    image1Class: "w-5/12",
    image2Class: "w-8/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/loc5.png",
    image2: "/images/loc6.png",
    title: "Google Maps Integration",
    description: "Integrate Google Maps API to provide dynamic, location-based services.",
    image1Class: "w-5/12",
    image2Class: "w-7/12 bottom-0 ",
    mb: "mb-10",
  },
  {
    image1: "/images/loc7.png",
    image2: "/images/loc8.png",
    title: "Dual User Mode",
    description: "Enable dual user modes to cater to both car drivers and mechanic admins.",
    image1Class: "w-5/12",
    image2Class: "w-6/12 -bottom-10 left-20",
    mb: "mb-10",
  },
  {
    image1: "/images/loc9.png",
    image2: "/images/loc10.png",
    title: "Firebase Auth",
    description: " Secure user authentication with Firebase Authentication for seamless login experiences, with dashboard admin view.",
    image1Class: "w-6/12 pr-16 rounded-2xl",
    image2Class: "w-9/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/loc11.png",
    image2: "/images/loc12.png",
    title: "Nearby Search",
    description: "Implement Google Maps API for real-time, nearby mechanic store search.",
    image1Class: "w-5/12",
    image2Class: "w-9/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/loc13.png",
    image2: "/images/loc14.png",
    title: "Cloud Messaging (Firebase)",
    description: "Enable sending signals to another device for mechanic requests, seamlessly managed on both foreground and background.",
    image1Class: "w-5/12",
    image2Class: "w-8/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/loc15.png",
    image2: "/images/loc16.png",
    title: "Real-time User Movement",
    description: "Display mechanics' real-time movement on the map towards user locations.",
    image1Class: "w-5/12 rounded-3xl",
    image2Class: "w-8/12 -bottom-14",
    mb: "mb-14",
  },
  {
    image1: "/images/loc17.png",
    image2: "/images/loc18.png",
    title: "Formik",
    description: "Optimize form handling with Formik for a streamlined user input experience.",
    image1Class: "w-5/12",
    image2Class: "w-9/12 -bottom-20",
    mb: "mb-20",
  },
  {
    image1: "/images/loc19.png",
    image2: "/images/loc20.png",
    title: "MOBX State Management",
    description: "Employ Mobx for precise state management in the React Native application.",
    image1Class: "w-6/12",
    image2Class: "w-6/12 -bottom-20",
    mb: "mb-20",
  },
];

export const weavifyFeatures = [
  {
    image1: "/images/weavify1.png",
    image2: "/images/weavify2.png",
    title: "Laravel Echo",
    description: "Laravel Echo is integrated to facilitate real-time communication between the server and clients.",
    image1Class: "w-6/12",
    image2Class: "w-9/12 -bottom-44",
    mb: "mb-44",
  },
  {
    image1: "/images/weavify3.png",
    image2: "/images/weavify4.png",
    title: "User Join Notifications",
    description: "User automatically joined to the group chat upon sign in.",
    image1Class: "w-6/12",
    image2Class: "w-9/12 -bottom-32",
    mb: "mb-32",
  },
  {
    image1: "/images/weavify5.png",
    image2: "/images/weavify6.png",
    title: "Broadcast Message",
    description: "Enable users to send messages that are instantly broadcasted to all connected clients, fostering real-time group communication.",
    image1Class: "w-8/12",
    image2Class: "w-10/12 -bottom-44",
    mb: "mb-44",
  },
  {
    image1: "/images/weavify7.png",
    title: "User Greetings",
    description: "Implement personalized greetings through broadcast events, delivering custom messages to specific users upon login or joining the chat.",
    image1Class: "w-11/12 mx-auto my-auto",
    image2Class: "w-11/12 -bottom-20",
    mb: "mb-20",
  }
];
